# Generated by Django 3.1.8 on 2021-04-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Fail'), (3, 'Patience'), (4, 'Congratulations')], default=1)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('marks', models.IntegerField()),
                ('image', models.ImageField(upload_to='question/')),
                ('answer', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
