# Generated by Django 4.1.7 on 2023-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(editable=False, max_length=700, unique=True),
        ),
    ]
